import type {LevelSpec} from '../types/levelContent';

/**
 * B2: handcrafted 6–20. difficultyOnCurve is band-relative (1–5) within 6–20 ramp.
 * failPointIntent + notesForQA support fail-point tagging for tuning.
 */
export const B2_HANDCRAFTED_LEVELS: LevelSpec[] = [
  {
    id: 6,
    name: 'Warm Six',
    batch: 'B2',
    difficultyOnCurve: 1,
    failPointIntent: 'path_choice',
    playfield: {w: 6, h: 6, start: {x: 0, y: 0}, goal: {x: 5, y: 5}},
    hazards: [{id: 'h1', kind: 'spike', x: 2, y: 2}],
  },
  {
    id: 7,
    name: 'Corridor',
    batch: 'B2',
    difficultyOnCurve: 1,
    failPointIntent: 'hazard_dodge',
    playfield: {w: 7, h: 5, start: {x: 0, y: 2}, goal: {x: 6, y: 2}},
    hazards: [
      {id: 'h1', kind: 'spike', x: 3, y: 1},
      {id: 'h2', kind: 'spike', x: 3, y: 3},
    ],
  },
  {
    id: 8,
    name: 'Double Lane',
    batch: 'B2',
    difficultyOnCurve: 2,
    failPointIntent: 'timing',
    playfield: {w: 7, h: 6, start: {x: 0, y: 3}, goal: {x: 6, y: 3}},
    hazards: [
      {id: 'h1', kind: 'spike', x: 2, y: 1},
      {id: 'h2', kind: 'spike', x: 4, y: 4},
    ],
  },
  {
    id: 9,
    name: 'Hook',
    batch: 'B2',
    difficultyOnCurve: 2,
    failPointIntent: 'path_choice',
    playfield: {w: 7, h: 7, start: {x: 0, y: 0}, goal: {x: 6, y: 6}},
    hazards: [
      {id: 'h1', kind: 'spike', x: 2, y: 4},
      {id: 'h2', kind: 'spike', x: 4, y: 2},
    ],
  },
  {
    id: 10,
    name: 'Midpoint Check',
    batch: 'B2',
    difficultyOnCurve: 2,
    failPointIntent: 'resource',
    playfield: {w: 8, h: 6, start: {x: 0, y: 2}, goal: {x: 7, y: 2}},
    hazards: [
      {id: 'h1', kind: 'spike', x: 2, y: 2, meta: {width: 2}},
      {id: 'h2', kind: 'spike', x: 5, y: 1},
    ],
  },
  {
    id: 11,
    name: 'Squeeze',
    batch: 'B2',
    difficultyOnCurve: 3,
    failPointIntent: 'timing',
    playfield: {w: 8, h: 6, start: {x: 0, y: 1}, goal: {x: 7, y: 4}},
    hazards: [
      {id: 'h1', kind: 'spike', x: 3, y: 0},
      {id: 'h2', kind: 'spike', x: 3, y: 5},
      {id: 'h3', kind: 'spike', x: 5, y: 2},
    ],
  },
  {
    id: 12,
    name: 'Lattice',
    batch: 'B2',
    difficultyOnCurve: 3,
    failPointIntent: 'hazard_dodge',
    playfield: {w: 8, h: 7, start: {x: 0, y: 3}, goal: {x: 7, y: 3}},
    hazards: [
      {id: 'h1', kind: 'spike', x: 2, y: 1},
      {id: 'h2', kind: 'spike', x: 2, y: 5},
      {id: 'h3', kind: 'spike', x: 5, y: 2},
      {id: 'h4', kind: 'spike', x: 5, y: 4},
    ],
  },
  {
    id: 13,
    name: 'Switchback',
    batch: 'B2',
    difficultyOnCurve: 3,
    failPointIntent: 'path_choice',
    playfield: {w: 8, h: 8, start: {x: 0, y: 0}, goal: {x: 7, y: 7}},
    hazards: [
      {id: 'h1', kind: 'spike', x: 2, y: 5},
      {id: 'h2', kind: 'spike', x: 5, y: 2},
      {id: 'h3', kind: 'spike', x: 3, y: 3, meta: {width: 2, height: 1}},
    ],
  },
  {
    id: 14,
    name: 'Gate',
    batch: 'B2',
    difficultyOnCurve: 4,
    failPointIntent: 'timing',
    playfield: {w: 9, h: 6, start: {x: 0, y: 2}, goal: {x: 8, y: 2}},
    hazards: [
      {id: 'h1', kind: 'spike', x: 2, y: 0},
      {id: 'h2', kind: 'spike', x: 2, y: 5},
      {id: 'h3', kind: 'spike', x: 5, y: 1},
      {id: 'h4', kind: 'spike', x: 5, y: 4},
    ],
  },
  {
    id: 15,
    name: 'Anchor',
    batch: 'B2',
    difficultyOnCurve: 4,
    failPointIntent: 'hazard_dodge',
    playfield: {w: 9, h: 7, start: {x: 0, y: 3}, goal: {x: 8, y: 3}},
    hazards: [
      {id: 'h1', kind: 'spike', x: 2, y: 1},
      {id: 'h2', kind: 'spike', x: 2, y: 5},
      {id: 'h3', kind: 'spike', x: 5, y: 2},
      {id: 'h4', kind: 'spike', x: 5, y: 4},
      {id: 'h5', kind: 'spike', x: 6, y: 3, meta: {phasing: 1}},
    ],
  },
  {
    id: 16,
    name: 'Weave',
    batch: 'B2',
    difficultyOnCurve: 4,
    failPointIntent: 'path_choice',
    playfield: {w: 9, h: 8, start: {x: 0, y: 0}, goal: {x: 8, y: 7}},
    hazards: [
      {id: 'h1', kind: 'spike', x: 2, y: 3},
      {id: 'h2', kind: 'spike', x: 4, y: 5},
      {id: 'h3', kind: 'spike', x: 6, y: 2},
      {id: 'h4', kind: 'spike', x: 6, y: 6},
    ],
  },
  {
    id: 17,
    name: 'Clockwork',
    batch: 'B2',
    difficultyOnCurve: 4,
    failPointIntent: 'timing',
    playfield: {w: 9, h: 7, start: {x: 0, y: 3}, goal: {x: 8, y: 3}},
    hazards: [
      {id: 'h1', kind: 'spike', x: 1, y: 1, meta: {phasing: 1}},
      {id: 'h2', kind: 'spike', x: 3, y: 5, meta: {phasing: 1}},
      {id: 'h3', kind: 'spike', x: 5, y: 1, meta: {phasing: 1}},
      {id: 'h4', kind: 'spike', x: 7, y: 5, meta: {phasing: 1}},
    ],
  },
  {
    id: 18,
    name: 'Braid',
    batch: 'B2',
    difficultyOnCurve: 5,
    failPointIntent: 'resource',
    playfield: {w: 10, h: 8, start: {x: 0, y: 4}, goal: {x: 9, y: 4}},
    hazards: [
      {id: 'h1', kind: 'spike', x: 2, y: 2},
      {id: 'h2', kind: 'spike', x: 2, y: 6},
      {id: 'h3', kind: 'spike', x: 4, y: 3},
      {id: 'h4', kind: 'spike', x: 4, y: 5},
      {id: 'h5', kind: 'spike', x: 7, y: 2},
      {id: 'h6', kind: 'spike', x: 7, y: 6},
    ],
  },
  {
    id: 19,
    name: 'Crescendo',
    batch: 'B2',
    difficultyOnCurve: 5,
    failPointIntent: 'hazard_dodge',
    playfield: {w: 10, h: 9, start: {x: 0, y: 4}, goal: {x: 9, y: 4}},
    hazards: [
      {id: 'h1', kind: 'spike', x: 2, y: 1},
      {id: 'h2', kind: 'spike', x: 2, y: 7},
      {id: 'h3', kind: 'spike', x: 4, y: 3},
      {id: 'h4', kind: 'spike', x: 4, y: 5},
      {id: 'h5', kind: 'spike', x: 6, y: 2},
      {id: 'h6', kind: 'spike', x: 6, y: 6},
    ],
  },
  {
    id: 20,
    name: 'Finale 20',
    batch: 'B2',
    difficultyOnCurve: 5,
    failPointIntent: 'timing',
    playfield: {w: 10, h: 9, start: {x: 0, y: 0}, goal: {x: 9, y: 8}},
    hazards: [
      {id: 'h1', kind: 'spike', x: 2, y: 3},
      {id: 'h2', kind: 'spike', x: 3, y: 6},
      {id: 'h3', kind: 'spike', x: 5, y: 2},
      {id: 'h4', kind: 'spike', x: 5, y: 6},
      {id: 'h5', kind: 'spike', x: 7, y: 4, meta: {width: 2}},
    ],
  },
];
